---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iCocos.
--- DateTime: 2018/10/11 上午11:29
---

--- @class Fence
local Fence = class("Fence")

---fenceGenerator 生成周边墙壁
---@param node table
---@param bound table
---@param callback table
local function fenceGenerator(node, bound, callback)

    for i = -bound, bound do
    
        local  sp = display.newSprite("fence.png")
        local posx, posy = callback(i)
        sp:setPosition(posx, posy)
        node:addChild(sp)

    end

end

---ctor  构造器
---@param bound table
---@param node table
function Fence:ctor(bound, node)
    
    self.bound = bound
    self.node = node

    fenceGenerator(node, bound, function(i)
        return Grid2Pos(i, bound)
    end)
    fenceGenerator(node, bound, function(i)
        return Grid2Pos(i, -bound)
    end)
    fenceGenerator(node, bound, function(i)
        return Grid2Pos(bound, i)
    end)
    fenceGenerator(node, bound, function(i)
        return Grid2Pos(-bound, i)
    end)

end

---CheckFenceCollide 撞墙逻辑
---@param x table
---@param y table
function Fence:CheckFenceCollide(x, y)

    return x == self.bound or x == -self.bound or y == self.bound or y == -self.bound

end

return Fence