---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iCocos.
--- DateTime: 2018/10/12 上午11:04
---

--- @class Commmon
local Commmon = class("Commmon")

----------------------------------------------------------------------------------------------------
---- 全局变量
----------------------------------------------------------------------------------------------------

L_D = "left"
R_D = "right"
U_D = "up"
D_D = "down"

----------------------------------------------------------------------------------------------------
---- 坐标转换
----------------------------------------------------------------------------------------------------

-- 或者二维位置变量
local cGridSize = 33
local scaleRate = 1 / display.contentScaleFactor

--- 坐标转换

--load view error: 	USE " cc.exports.Grid2Pos = value " INSTEAD OF SET GLOBAL VARIABLE
---Grid2Pos
---@param x table
---@param y table
function Grid2Pos(x, y)

    local visibleSize = cc.Director:getInstance():getVisibleSize()
    local visibleOrigin = cc.Director:getInstance():getVisibleOrigin()

    local finalX = visibleOrigin.x + visibleSize.width/2 + x * cGridSize *scaleRate
    local finalY = visibleOrigin.y + visibleSize.height/2 + y * cGridSize *scaleRate

    return finalX, finalY

end


return Commmon