---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iCocos.
--- DateTime: 2018/10/11 上午11:29
---

---@class Body
local Body = class("Body")

--- ctor 构造函数
---@param snake 蛇的本体
---@param x 逻辑坐标X
---@param y 逻辑坐标Y
---@param node 结点
---@param isHead 是否是头部
function Body:ctor(snake, x, y, node, isHead)

    self.snake = snake
    self.X = x
    self.Y = y

    if isHead then
        -- 更新方法 -- cc.Sprite:create("head.png")
        self.sp = display.newSprite("head.png")
    else
        self.sp = display.newSprite("body.png")
    end

    node:addChild(self.sp)

    self:update()

end

--- 更新身体
---@return table
function Body:update()

    local posx, posy = Grid2Pos(self.X, self.Y)

    self.sp:setPosition(posx, posy)

end

return Body